version:  '3.5'
services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        ports:
            - "3306:3306"        
        volumes:
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password

    nginx:
        image: nginx:alpine
        restart: on-failure
        volumes:
            - '../public/:/usr/src/app'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 80:80
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        depends_on:
            - mysql            
        volumes:
            - '../:/usr/src/app'
        restart: on-failure
        user: 1000:1000
